<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Acton</string>
    <key>fileTypes</key>
    <array>
        <string>act</string>
    </array>
    <key>scopeName</key>
    <string>source.acton</string>
	<key>uuid</key>
	<string>F0BF8B90-4A9B-4A31-AD0D-A521BD41D987</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#comments</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#keywords</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#strings</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#numbers</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#operators</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#functions</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#types</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#decorators</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>comments</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>#.*$</string>
                    <key>name</key>
                    <string>comment.line.number-sign.acton</string>
                </dict>
            </array>
        </dict>
        <key>strings</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key>
                    <string>string.quoted.triple.double.acton</string>
                    <key>begin</key>
                    <string>"""</string>
                    <key>end</key>
                    <string>"""</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>string.quoted.triple.single.acton</string>
                    <key>begin</key>
                    <string>&apos;&apos;&apos;</string>
                    <key>end</key>
                    <string>&apos;&apos;&apos;</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>string.quoted.double.acton</string>
                    <key>begin</key>
                    <string>&quot;</string>
                    <key>end</key>
                    <string>&quot;</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>name</key>
                            <string>constant.character.escape.acton</string>
                            <key>match</key>
                            <string>\\[\\&quot;&apos;abfnrtv]|\\x[0-9A-Fa-f]{2}|\\[0-7]{1,3}|\\u[0-9A-Fa-f]{4}|\\U[0-9A-Fa-f]{8}</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>name</key>
                    <string>string.quoted.single.acton</string>
                    <key>begin</key>
                    <string>&apos;</string>
                    <key>end</key>
                    <string>&apos;</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>name</key>
                            <string>constant.character.escape.acton</string>
                            <key>match</key>
                            <string>\\[\\&quot;&apos;abfnrtv]|\\x[0-9A-Fa-f]{2}|\\[0-7]{1,3}</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>keywords</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key>
                    <string>keyword.control.acton</string>
                    <key>match</key>
                    <string>\b(if|elif|else|while|for|in|try|except|finally|with|return|break|continue|pass|raise|yield|from|import|as|assert|await|async|del|lambda)\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.declaration.acton</string>
                    <key>match</key>
                    <string>\b(def|class|actor|protocol|extension|var)\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>constant.language.acton</string>
                    <key>match</key>
                    <string>\b(True|False|None|NotImplemented|\.\.\.)\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.effect.acton</string>
                    <key>match</key>
                    <string>\b(proc|mut|pure|action)\b</string>
                </dict>
            </array>
        </dict>
        <key>operators</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.arithmetic.acton</string>
                    <key>match</key>
                    <string>\+|-|\*|/|//|%|@|\*\*</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.comparison.acton</string>
                    <key>match</key>
                    <string>==|!=|&lt;&gt;|&lt;|&gt;|&lt;=|&gt;=|\b(is not|is|in|not in)\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.logical.acton</string>
                    <key>match</key>
                    <string>\b(and|or|not)\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.bitwise.acton</string>
                    <key>match</key>
                    <string>&amp;|\||\^|~|&lt;&lt;|&gt;&gt;</string>
                </dict>
            </array>
        </dict>
        <key>numbers</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.integer.hexadecimal.acton</string>
                    <key>match</key>
                    <string>\b0x[0-9a-fA-F]+\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.integer.octal.acton</string>
                    <key>match</key>
                    <string>\b0o[0-7]+\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.float.acton</string>
                    <key>match</key>
                    <string>\b\d+\.\d*([eE][+-]?\d+)?j?\b|\b\.\d+([eE][+-]?\d+)?j?\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>constant.numeric.integer.decimal.acton</string>
                    <key>match</key>
                    <string>\b\d+\b</string>
                </dict>
            </array>
        </dict>
        <key>functions</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.acton</string>
                    <key>match</key>
                    <string>(?&lt;=def\s)[a-zA-Z_][a-zA-Z0-9_]*</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>support.function.builtin.acton</string>
                    <key>match</key>
                    <string>\b(isinstance)\b</string>
                </dict>
            </array>
        </dict>
        <key>types</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.acton</string>
                    <key>match</key>
                    <string>(?&lt;=:)\s*([A-Z][a-zA-Z0-9_]*)</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.class.acton</string>
                    <key>match</key>
                    <string>(?&lt;=class\s)[A-Z][a-zA-Z0-9_]*</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.protocol.acton</string>
                    <key>match</key>
                    <string>(?&lt;=protocol\s)[A-Z][a-zA-Z0-9_]*</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.actor.acton</string>
                    <key>match</key>
                    <string>(?&lt;=actor\s)[A-Z][a-zA-Z0-9_]*</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>entity.name.type.generic.acton</string>
                    <key>match</key>
                    <string>\b[A-Z]\d*\b</string>
                </dict>
            </array>
        </dict>
        <key>decorators</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.decorator.acton</string>
                    <key>match</key>
                    <string>@(property|staticmethod|static)</string>
                </dict>
            </array>
        </dict>
    </dict>
</dict>
</plist>
