name: Build & Package VS Code Extension

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # Push events to tags matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Package Extension
      run: vsce package

    - name: Get Extension Information
      id: get-extension-info
      run: |
        VSIX_PATH=$(ls *.vsix)
        echo "VSIX_PATH=$VSIX_PATH" >> $GITHUB_ENV
        echo "VSIX_NAME=$(basename $VSIX_PATH)" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: extension
        path: ${{ env.VSIX_PATH }}

    # Create GitHub Release when a tag is pushed
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.VSIX_PATH }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true

    # Publish to VS Code Marketplace when a tag is pushed
    - name: Publish to Marketplace
      if: startsWith(github.ref, 'refs/tags/')
      run: vsce publish -p ${{ secrets.VSCE_PAT }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
